//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIS_POC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OTIS_POCEntitiesNew : DbContext
    {
        public OTIS_POCEntitiesNew()
            : base("name=OTIS_POCEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Financials_by_Brand> Financials_by_Brands { get; set; }
        public virtual DbSet<tblApprovalType> tblApprovalTypes { get; set; }
        public virtual DbSet<tblApprover> tblApprovers { get; set; }
        public virtual DbSet<tblContract> tblContracts { get; set; }
        public virtual DbSet<tblContractType> tblContractTypes { get; set; }
        public virtual DbSet<tblRegion> tblRegions { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWholesaler> tblWholesalers { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<Vw_Users> Vw_Users { get; set; }
    }
}
