//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIS_POC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprovalType
    {
        public int id { get; set; }
        public string ApproveType { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> NSOrder { get; set; }
        public string Description { get; set; }
    }
}
