//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIS_POC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprover
    {
        public int id { get; set; }
        public Nullable<int> Role { get; set; }
        public string Region { get; set; }
        public string Brand { get; set; }
        public string username { get; set; }
    
        public virtual tblApprover tblApprovers1 { get; set; }
        public virtual tblApprover tblApprover1 { get; set; }
    }
}
