//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIS_POC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        public string Contract_Code { get; set; }
        public string Outlet_Name { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string CDOS { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public Nullable<System.DateTime> Corrected_End_Date { get; set; }
        public Nullable<int> Real_Month { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> NSV { get; set; }
        public Nullable<double> GP { get; set; }
        public Nullable<double> Vol_related { get; set; }
        public Nullable<decimal> Non_Vol_related { get; set; }
        public Nullable<double> Non_Vol_FTT { get; set; }
        public Nullable<double> FTT { get; set; }
        public Nullable<double> CAAP_pre_A_P { get; set; }
        public Nullable<double> A_P { get; set; }
        public Nullable<double> CAAP { get; set; }
        public Nullable<double> Investment { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
        public Nullable<int> Payment_Months { get; set; }
        public string Legal_Name { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> ConsF { get; set; }
        public Nullable<double> Display { get; set; }
        public Nullable<double> Listing { get; set; }
        public Nullable<double> Promo { get; set; }
        public Nullable<double> Sponsor { get; set; }
        public Nullable<double> Party { get; set; }
        public Nullable<double> POSM { get; set; }
        public Nullable<double> Other { get; set; }
        public string SchBonus { get; set; }
        public string SchDisplay { get; set; }
        public string SchListing { get; set; }
        public string SchPromo { get; set; }
        public string SchSponsor { get; set; }
        public string SchParty { get; set; }
        public string SchPOSM { get; set; }
        public string SchOther { get; set; }
        public string SchConsF { get; set; }
        public string PM_Bonus { get; set; }
        public string PM_Display { get; set; }
        public string PM_Listing { get; set; }
        public string PM_Promo { get; set; }
        public string PM_Sponsor { get; set; }
        public string PM_Party { get; set; }
        public string PM_ConsF { get; set; }
        public string PM_POSM { get; set; }
        public Nullable<bool> AlcoholPermitObtained { get; set; }
        public Nullable<bool> ServiceInvoiceAvailable { get; set; }
        public Nullable<bool> TaxRegistrationNational { get; set; }
        public Nullable<bool> TaxRegistrationLocal { get; set; }
        public Nullable<bool> BusinessLicense { get; set; }
        public Nullable<bool> OrganisationCodeCertificate { get; set; }
        public Nullable<bool> IDcard { get; set; }
        public Nullable<bool> TaxCertificate { get; set; }
        public Nullable<bool> BankAccountPermission { get; set; }
        public Nullable<int> Outlet { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ContractType { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> CashPayableOutlet { get; set; }
        public Nullable<bool> ReplacingCompetition { get; set; }
        public string SchRPB { get; set; }
        public string PM_RPB { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
    }
}
