//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIS_POC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWholesaler
    {
        public int code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> maxdiscount { get; set; }
        public string Wholesaler_Ad_agency { get; set; }
        public Nullable<int> Tier { get; set; }
        public string Business_address { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public Nullable<bool> C2nd_tier_wholesalers_supported { get; set; }
        public Nullable<bool> Outlets_supported { get; set; }
        public string Primary_contact { get; set; }
        public string Telephone_number { get; set; }
        public string Primary_DCL_contact { get; set; }
        public Nullable<bool> CashPool { get; set; }
        public string SAPnumber { get; set; }
        public Nullable<bool> ApplyFixedDiscount { get; set; }
        public string WholesalerCode { get; set; }
    }
}
