//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIS_POC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int VENUE_CODE { get; set; }
        public string Code { get; set; }
        public Nullable<double> Excel_Number { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City_Ch { get; set; }
        public string City { get; set; }
        public string Outlet_Name { get; set; }
        public string Channel { get; set; }
        public string CDOS { get; set; }
        public string Sub_type { get; set; }
        public string Class { get; set; }
        public string Size { get; set; }
        public Nullable<double> Number_of_tables { get; set; }
        public Nullable<double> Number_of_rooms { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Owner { get; set; }
        public string Owner_s_telephone { get; set; }
        public string Contact { get; set; }
        public string Contact_s_telephone { get; set; }
        public string Sales_Man { get; set; }
        public Nullable<int> Distributor { get; set; }
        public bool Contract_Outlet { get; set; }
        public bool Part_of_a_chain { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public Nullable<bool> Multi_venue { get; set; }
        public Nullable<long> BottlesOfSales { get; set; }
        public string Business_license_address { get; set; }
        public Nullable<int> C2ndDistributor { get; set; }
        public string LegalName { get; set; }
        public string StoreName { get; set; }
    }
}
